pipeline {
    agent any

    stages {
        stage('Cron Execute') {
            steps {
                sh './cronDBUpdate.exe'
            }
            post {
                success {
                    echo '성공~'
                }
                failure {
                    echo '실패...'
                }
            }
        }
    }
}